[package]
name = "sc2-eval"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "^0.4.38"
clap = { version = "4.0", features = ["derive"] }
env_logger = "^0.10"
indicatif = "^0.17"
log = "^0.4"
