name: "Basic checks for the experiment repo"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

defaults:
  run:
    shell: bash

# Cancel previous running actions for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Set up Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.80.1
          profile: minimal
          override: true
      - name: "Run cargo fmt check"
        run: cargo fmt --all -- --check
      - name: "Run cargo clippy"
        run: cargo clippy -- -D warnings

