name: "Basic checks for the experiment repo"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

defaults:
  run:
    shell: bash

# Cancel previous running actions for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint_and_format:
    runs-on: ubuntu-24.04

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install apt deps"
        run: sudo apt install -y libfontconfig1-dev
      - name: "Fix rust version"
        run: rustup default 1.83.0
      - name: "Run cargo fmt check"
        run: cargo fmt --all -- --check
      - name: "Run cargo clippy"
        run: cargo clippy -- -D warnings

